
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - openapi.pivotal.io
  resources:
  - requests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openapi.pivotal.io
  resources:
  - requests/status
  verbs:
  - get
  - patch
  - update
